# Generated by Django 4.2.5 on 2023-09-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_gender_prospectprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmationcode',
            name='code_type',
        ),
        migrations.RemoveField(
            model_name='confirmationcode',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='confirmationcode',
            name='confirmation_type',
            field=models.CharField(choices=[('account_verification', 'Account verification'), ('forgot_password', 'Forgot password')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='confirmationcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='confirmationcode',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
