# Generated by Django 4.2.5 on 2024-01-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_agentprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='line_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='we_chat_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='whats_app_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='line_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='we_chat_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='whats_app_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='company_logo',
            field=models.ImageField(max_length=1000, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='company_logo',
            field=models.ImageField(max_length=1000, null=True, upload_to=''),
        ),
    ]
