# Generated by Django 4.2.5 on 2024-02-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_agentprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospectprofile',
            name='picture',
        ),
    ]
