# Generated by Django 4.2.5 on 2024-05-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_prospectprofile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectprofile',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
