# Generated by Django 4.2.5 on 2024-05-29 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_agentprofile_line_link_agentprofile_we_chat_link_and_more'),
        ('user', '0007_remove_prospectprofile_picture'),
    ]

    operations = [
    ]
