# Generated by Django 4.2.5 on 2024-06-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_prospectprofile_latitude_prospectprofile_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentprofile',
            old_name='company_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='developerprofile',
            old_name='company_address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='company_logo',
            field=models.ImageField(max_length=1000, null=True, upload_to='developer_or_agent_company_logo/'),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='company_logo',
            field=models.ImageField(max_length=1000, null=True, upload_to='developer_or_agent_company_logo/'),
        ),
        migrations.AlterField(
            model_name='prospectprofile',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
