# Generated by Django 4.2.5 on 2024-05-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_merge_20240529_0226'),
        ('user', '0008_prospectprofile_latitude_prospectprofile_longitude'),
    ]

    operations = [
    ]
