# Generated by Django 4.2.5 on 2024-06-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_merge_20240529_1028'),
        ('user', '0009_rename_company_address_agentprofile_address_and_more'),
    ]

    operations = [
    ]
