# Generated by Django 4.2.5 on 2024-06-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_merge_20240601_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='company_logo',
            field=models.ImageField(max_length=1000, null=True, upload_to='developer_or_agent_company_logo/'),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='company_logo',
            field=models.ImageField(max_length=1000, null=True, upload_to='developer_or_agent_company_logo/'),
        ),
    ]
