# Generated by Django 4.2.5 on 2024-06-02 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_merge_20240601_0947'),
        ('user', '0011_alter_agentprofile_company_logo_and_more'),
    ]

    operations = [
    ]
