# Generated by Django 4.2.5 on 2024-10-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_merge_20240602_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', max_length=50),
        ),
    ]
