# Generated by Django 4.2.5 on 2024-10-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_auth_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('developer', 'Developer'), ('agent', 'Agent'), ('prospect', 'Prospect')], max_length=50),
        ),
    ]
