# Generated by Django 4.2.5 on 2025-10-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
