# Generated by Django 4.2.5 on 2023-10-11 03:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=3000, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('condos', 'Condos'), ('house', 'House')], max_length=100, null=True)),
                ('total_units_for_sale', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('address', models.CharField(max_length=500)),
                ('project_total_area', models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_floors', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('construction_year', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('have_lake_or_river_view', models.BooleanField(default=False)),
                ('have_guard_house', models.BooleanField(default=False)),
                ('have_sauna', models.BooleanField(default=False)),
                ('have_sky_lounge', models.BooleanField(default=False)),
                ('have_grocery', models.BooleanField(default=False)),
                ('have_fitness_area', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuildingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('image', 'Image'), ('floor_plan', 'Floor plan'), ('unit_floor_plan', 'Unit floor plan'), ('master_plan', 'Master plan'), ('video', 'Video')], max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='building_media/')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.building')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
