# Generated by Django 4.2.5 on 2023-10-11 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_alter_buildingmedia_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='construction_year',
            field=models.IntegerField(default=1930, null=True, validators=[django.core.validators.MinValueValidator(1930)]),
        ),
    ]
