# Generated by Django 4.2.5 on 2023-10-11 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_alter_building_construction_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='building',
            name='project_total_area',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_floors',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_units_for_sale',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
