# Generated by Django 4.2.5 on 2023-10-14 12:48

import building.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0006_alter_buildingmedia_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingmedia',
            name='file',
            field=models.FileField(null=True, upload_to=building.models.BuildingMedia.upload_to),
        ),
    ]
