# Generated by Django 4.2.5 on 2023-10-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0008_building_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='district',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='province',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='sub_district',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
