# Generated by Django 4.2.5 on 2023-10-28 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0009_building_district_building_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
