# Generated by Django 4.2.5 on 2023-11-15 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0011_buildingreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='price',
            new_name='highest_price',
        ),
        migrations.AddField(
            model_name='building',
            name='lowest_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
