# Generated by Django 4.2.5 on 2023-12-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0012_rename_price_building_highest_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='have_lake_or_river_view',
            new_name='have_river_view',
        ),
        migrations.AddField(
            model_name='building',
            name='furnishing',
            field=models.CharField(choices=[('partly', 'Partly'), ('fully', 'Fully')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='have_city_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='have_freehold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='have_infinity_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='have_leasehold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='have_mountain_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='have_sea_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='have_unblocked_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='quota',
            field=models.CharField(choices=[('thai', 'Thai'), ('foreign', 'Foreign')], max_length=100, null=True),
        ),
    ]
