# Generated by Django 4.2.5 on 2023-12-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0013_rename_have_lake_or_river_view_building_have_river_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='have_pets_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
