# Generated by Django 4.2.5 on 2023-12-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0014_building_have_pets_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
