# Generated by Django 4.2.5 on 2023-12-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0015_building_latitude_building_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
