# Generated by Django 4.2.5 on 2023-12-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0016_building_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='popular',
        ),
        migrations.CreateModel(
            name='PopularBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.building')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
