# Generated by Django 4.2.5 on 2023-12-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0018_alter_popularbuilding_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='have_access_to_ARL',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='have_access_to_BTS_or_MRT',
            field=models.BooleanField(default=False),
        ),
    ]
