# Generated by Django 4.2.5 on 2024-01-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0019_building_have_access_to_arl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='have_city_view',
        ),
        migrations.RemoveField(
            model_name='building',
            name='have_mountain_view',
        ),
        migrations.RemoveField(
            model_name='building',
            name='have_river_view',
        ),
        migrations.RemoveField(
            model_name='building',
            name='have_sea_view',
        ),
        migrations.RemoveField(
            model_name='building',
            name='have_unblocked_view',
        ),
        migrations.AddField(
            model_name='building',
            name='view',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='have_access_to_ARL',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='have_access_to_BTS_or_MRT',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
