# Generated by Django 4.2.5 on 2024-01-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0020_remove_building_have_city_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingmedia',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('floor_plan', 'Floor plan'), ('unit_floor_plan', 'Unit floor plan'), ('master_plan', 'Master plan'), ('video', 'Video'), ('facilities_virtual_tour', 'Facilities virtual tour'), ('location_virtual_tour', 'Location virtual tour'), ('aerial_drone_video', 'Aerial drone video')], max_length=100, null=True),
        ),
    ]
