# Generated by Django 4.2.5 on 2024-02-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0021_alter_buildingmedia_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='facility_view',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='location_view',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
