# Generated by Django 4.2.5 on 2024-02-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0022_building_facility_view_building_location_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingmedia',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('floor_plan', 'Floor plan'), ('unit_floor_plan', 'Unit floor plan'), ('master_plan', 'Master plan'), ('video', 'Video'), ('aerial_drone_video', 'Aerial drone video')], max_length=100, null=True),
        ),
    ]
