# Generated by Django 4.2.5 on 2024-02-28 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0023_alter_buildingmedia_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='have_access_to_ARL',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='building',
            name='have_access_to_BTS_or_MRT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
