# Generated by Django 4.2.5 on 2024-03-05 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0025_alter_building_have_access_to_arl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularbuilding',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='populars', to='building.building'),
        ),
    ]
