# Generated by Django 4.2.5 on 2024-03-05 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('building', '0026_alter_popularbuilding_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingreview',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='building.building'),
        ),
        migrations.AlterField(
            model_name='buildingreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
