# Generated by Django 4.2.5 on 2024-03-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0027_alter_buildingreview_building_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='have_access_to_ARL',
            new_name='distance_from_location_to_ARL',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='have_access_to_BTS_or_MRT',
            new_name='distance_from_location_to_BTS_or_MRT',
        ),
    ]
