# Generated by Django 4.2.5 on 2024-05-30 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0028_rename_have_access_to_arl_building_distance_from_location_to_arl_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopularBuilding',
        ),
    ]
