# Generated by Django 4.2.5 on 2024-05-30 07:19

import django.core.validators
from django.db import migrations, models
import utils.helper_func


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0029_delete_popularbuilding'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='status',
            field=models.CharField(choices=[('to_be_commenced', 'To Be Commenced'), ('under_construction', 'Under Construction'), ('completed', 'Completed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='construction_year',
            field=models.IntegerField(blank=True, default=2000, null=True, validators=[django.core.validators.MinValueValidator(2000), utils.helper_func.validate_max_current_year]),
        ),
    ]
