# Generated by Django 4.2.5 on 2024-06-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0030_building_status_alter_building_construction_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingmedia',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('unit_floor_plan', 'Unit floor plan'), ('master_plan', 'Master plan'), ('video', 'Video'), ('aerial_drone_video', 'Aerial drone video')], max_length=100, null=True),
        ),
    ]
