# Generated by Django 4.2.5 on 2024-06-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0031_alter_buildingmedia_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='sub_district',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
