# Generated by Django 4.2.5 on 2024-06-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0032_alter_building_sub_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('condo', 'Condo'), ('single_house', 'Single House'), ('townhouse', 'Townhouse'), ('apartment', 'Apartment'), ('sales_area', 'Sales area'), ('office', 'Office'), ('warehouse_factory', 'Warehouse-Factory')], help_text='Select a sub type based on the selected type.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.CharField(choices=[('residence', 'Residence'), ('commercial', 'Commercial')], max_length=100, null=True),
        ),
    ]
