# Generated by Django 4.2.5 on 2024-07-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0033_building_sub_type_alter_building_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('bungalow_villa', 'Bungalow/Villa'), ('apartment_conod_service_residence', 'Apartment/Conod/Service Residence'), ('semi_detached_house', 'Semi-Detached House'), ('terrace_link_house', 'Terrace/Link House'), ('residentail_land', 'Residentail Land'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('aqricultural_land', 'Aqricultural Land'), ('other', 'Other')], help_text='Select a sub type based on the selected type.', max_length=100, null=True),
        ),
    ]
