# Generated by Django 4.2.5 on 2024-07-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0034_alter_building_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('bungalow_villa', 'Bungalow/Villa'), ('apartment_condo_service_residence', 'Apartment/Condo/Service Residence'), ('semi_detached_house', 'Semi-Detached House'), ('terrace_link_house', 'Terrace/Link House'), ('residential_land', 'Residential Land'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('agricultural_land', 'Agricultural Land'), ('other', 'Other')], help_text='Select a sub type based on the selected type.', max_length=100, null=True),
        ),
    ]
