# Generated by Django 4.2.5 on 2025-09-22 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0035_alter_building_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='distance_from_location_to_ARL',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distance from location to ARL (KM)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='distance_from_location_to_BTS_or_MRT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distance from location to BTS or MRT (KM)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='have_fitness_area',
            field=models.BooleanField(default=False, verbose_name='Fitness Area'),
        ),
        migrations.AlterField(
            model_name='building',
            name='have_freehold',
            field=models.BooleanField(default=False, verbose_name='Freehold'),
        ),
        migrations.AlterField(
            model_name='building',
            name='have_grocery',
            field=models.BooleanField(default=False, verbose_name='Grocery'),
        ),
        migrations.AlterField(
            model_name='building',
            name='have_guard_house',
            field=models.BooleanField(default=False, verbose_name='Guard House'),
        ),
        migrations.AlterField(
            model_name='building',
            name='have_infinity_pool',
            field=models.BooleanField(default=False, verbose_name='Infinity Pool'),
        ),
        migrations.AlterField(
            model_name='building',
            name='have_leasehold',
            field=models.BooleanField(default=False, verbose_name='Leasehold'),
        ),
        migrations.AlterField(
            model_name='building',
            name='have_pets_allowed',
            field=models.BooleanField(default=False, verbose_name='Pets Allowed'),
        ),
        migrations.AlterField(
            model_name='building',
            name='have_sauna',
            field=models.BooleanField(default=False, verbose_name='Sauna'),
        ),
        migrations.AlterField(
            model_name='building',
            name='have_sky_lounge',
            field=models.BooleanField(default=False, verbose_name='Sky Lounge'),
        ),
        migrations.AlterField(
            model_name='building',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
