# Generated by Django 4.2.5 on 2025-10-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0036_alter_building_distance_from_location_to_arl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='highest_price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='lowest_price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
