# Generated by Django 4.2.27 on 2025-12-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0037_alter_building_highest_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingreview',
            name='review_text',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
