from .media import BuildingMediaSerializer
from .default import BuildingSerializer
from .list import BuildingListSerializer
from .create_n_update import BuildingCreateAndUpdateSerializer
from .details import BuildingDetailsSerializer
from .info_for_property import BuildingInfoForPropertySerializer
from .various_feature import BuildingVariousFeatureSerializer
from .review import BuildingReviewSerializer