# Generated by Django 4.2.5 on 2024-07-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipdata',
            name='last_time_updated',
        ),
        migrations.AddField(
            model_name='ipdata',
            name='last_time_checked_by_proxycheck',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
