# Generated by Django 4.2.5 on 2024-07-17 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ipdata', '0002_remove_ipdata_last_time_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
