# Generated by Django 4.2.5 on 2024-03-26 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=2000, null=True)),
                ('social_media', models.CharField(choices=[('youtube', 'Youtube'), ('titTok', 'TitTok'), ('instagram', 'Instagram')], max_length=30, null=True)),
                ('category', models.CharField(choices=[('advice', 'Advice'), ('info', 'Info'), ('tour', 'Tour')], max_length=30, null=True)),
                ('status', models.CharField(default='active', max_length=30)),
                ('details', models.TextField(blank=True, max_length=3000, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
