# Generated by Django 4.2.5 on 2024-06-02 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0030_spotlightproperty'),
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reel',
            name='details',
        ),
        migrations.AddField(
            model_name='reel',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reels', to='property.property'),
        ),
    ]
