# Generated by Django 4.2.5 on 2024-03-28 06:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='url',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
