# Generated by Django 4.2.5 on 2024-07-15 11:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0033_discountproperty_unique_discount_property'),
        ('advertise', '0002_remove_reel_details_reel_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('home', 'Home'), ('search', 'Search'), ('details', 'Details')], max_length=25, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('run_time', models.DurationField(default=datetime.timedelta(0), help_text='In seconds')),
                ('number_of_clicked', models.PositiveIntegerField(default=0)),
                ('view_time', models.DurationField(default=datetime.timedelta(0), help_text='In seconds')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
