# Generated by Django 4.2.5 on 2024-03-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_alter_reel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
