# Generated by Django 4.2.5 on 2024-07-17 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0033_discountproperty_unique_discount_property'),
        ('advertise', '0003_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.CreateModel(
            name='AdViewerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('view_from_this_location', models.IntegerField(default=0)),
                ('advertisement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertise.advertisement')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvertisementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=500, null=True)),
                ('advertisement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertise.advertisement')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.property')),
                ('user_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdDemography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('male_visitors', models.PositiveIntegerField(default=0)),
                ('female_visitors', models.PositiveIntegerField(default=0)),
                ('advertisement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='advertise.advertisement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
