# Generated by Django 4.2.5 on 2024-07-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0004_alter_advertisement_property_adviewerlocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
