# Generated by Django 4.2.5 on 2024-07-25 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0005_advertisement_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='end_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='run_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='view_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
