# Generated by Django 4.2.5 on 2024-07-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0006_alter_advertisement_end_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='run_time',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ad_run_duration',
            field=models.PositiveIntegerField(default=0, help_text='How many days this ad will run'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped')], default='running', max_length=25),
        ),
    ]
