# Generated by Django 4.2.5 on 2024-07-28 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0007_remove_advertisement_end_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='type',
            new_name='ad_location',
        ),
    ]
