# Generated by Django 4.2.5 on 2024-09-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0008_rename_type_advertisement_ad_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ad_location',
            field=models.CharField(choices=[('home', 'Home'), ('search', 'Search'), ('details', 'Details'), ('blog', 'Blog')], max_length=25, null=True),
        ),
    ]
