# Generated by Django 4.2.5 on 2024-10-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0009_alter_advertisement_ad_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ad_location',
            field=models.CharField(choices=[('home', 'Home'), ('search', 'Search'), ('details_topbar', 'Details Topbar'), ('details_sidebar', 'Details Sidebar'), ('blog', 'Blog')], max_length=25, null=True),
        ),
    ]
