# Generated by Django 4.2.5 on 2025-07-08 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0010_alter_advertisement_ad_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.PositiveIntegerField(default=1, help_text='Position of the advertisement in the ad location', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
