# Generated by Django 4.2.5 on 2025-08-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0011_alter_advertisement_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='banner',
            field=models.ImageField(null=True, upload_to='advertisement/banner/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='number_of_clicked',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of clicks'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('running', 'Active'), ('stopped', 'Inactive')], default='running', max_length=25),
        ),
    ]
