# Generated by Django 4.2.5 on 2025-09-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0012_advertisement_banner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addemography',
            options={'verbose_name_plural': 'Advertisement Demographic'},
        ),
        migrations.AlterModelOptions(
            name='adviewerlocation',
            options={'verbose_name_plural': 'Advertisement Viewer Locations'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
