# Generated by Django 4.2.5 on 2025-09-11 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('advertise', '0014_remove_advertisement_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'building'), ('model', 'building')), models.Q(('app_label', 'property'), ('model', 'property')), _connector='OR')), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
