# Generated by Django 4.2.5 on 2025-09-11 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('advertise', '0016_remove_advertisementlog_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adviewerlocation',
            name='property',
        ),
        migrations.AddField(
            model_name='adviewerlocation',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'building'), ('model', 'building')), models.Q(('app_label', 'property'), ('model', 'property')), _connector='OR')), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='adviewerlocation',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
