# Generated by Django 4.2.5 on 2025-12-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0017_remove_adviewerlocation_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ad_location',
            field=models.CharField(choices=[('home', 'Home'), ('search', 'Search'), ('search_inline', 'Search Inline'), ('details_topbar', 'Details Topbar'), ('details_sidebar', 'Details Sidebar'), ('map_below', 'Map Below'), ('blog', 'Blog')], max_length=25, null=True),
        ),
    ]
