# Generated by Django 4.2.5 on 2023-10-15 07:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('building', '0008_building_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_id', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=3000, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('floor_number', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_area', models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('bedroom', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('balcony', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('car_parking', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='building.building')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('image', 'Image'), ('unit_floor_plan', 'Unit floor plan'), ('video', 'Video')], max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to=property.models.PropertyMedia.upload_to)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='property.property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
