# Generated by Django 4.2.5 on 2023-10-15 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='balcony',
            new_name='number_of_balcony',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='bedroom',
            new_name='number_of_bathroom',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='car_parking',
            new_name='number_of_bedroom',
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_car_parking',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
