# Generated by Django 4.2.5 on 2023-10-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_compareproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymedia',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('unit_plan', 'Unit plan'), ('video', 'Video')], max_length=100, null=True),
        ),
    ]
