# Generated by Django 4.2.5 on 2023-10-28 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_propertymedia_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
