# Generated by Django 4.2.5 on 2023-10-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymedia',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=100, null=True),
        ),
    ]
