# Generated by Django 4.2.5 on 2023-11-09 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_agentprofile_email_and_more'),
        ('property', '0007_property_price_per_sqm_alter_property_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectFavoriteProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('prospect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.prospectprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
