# Generated by Django 4.2.5 on 2023-11-09 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_agentprofile_email_and_more'),
        ('property', '0008_prospectfavoriteproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectfavoriteproperty',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.prospectprofile'),
        ),
    ]
