# Generated by Django 4.2.5 on 2023-12-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_prospectfavoriteproperty_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='balcony_direction',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='have_access_to_ARL',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='have_access_to_BTS_or_MRT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='have_bathtub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='have_duplex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='have_owner_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='have_tenant_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='have_vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='main_door_direction',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='tenant_occupied_validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_position',
            field=models.CharField(choices=[('left_corner', 'Left Corner'), ('right_corner', 'Right Corner'), ('center', 'Center')], max_length=100, null=True),
        ),
    ]
