# Generated by Django 4.2.5 on 2023-12-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_property_balcony_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='newly_created',
            field=models.BooleanField(default=False),
        ),
    ]
