# Generated by Django 4.2.5 on 2023-12-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_property_newly_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
