# Generated by Django 4.2.5 on 2023-12-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_property_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='discount_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
