# Generated by Django 4.2.5 on 2023-12-18 07:00

from django.db import migrations, models
import utils.general_func


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_property_discount_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='discount_period',
            field=models.DateField(blank=True, null=True, validators=[utils.general_func.validate_date_format]),
        ),
        migrations.AlterField(
            model_name='property',
            name='tenant_occupied_validity',
            field=models.DateField(blank=True, null=True, validators=[utils.general_func.validate_date_format]),
        ),
    ]
