# Generated by Django 4.2.5 on 2023-12-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_property_discount_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='discount_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='tenant_occupied_validity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
