# Generated by Django 4.2.5 on 2023-12-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_popularproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularproperty',
            options={'verbose_name_plural': 'Popular properties'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='popular',
        ),
    ]
