# Generated by Django 4.2.5 on 2023-12-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_alter_popularproperty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularproperty',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.property'),
        ),
    ]
