# Generated by Django 4.2.5 on 2023-12-21 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_remove_property_newly_created_newlycreatedproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newlycreatedproperty',
            options={'verbose_name_plural': 'Newly created properties'},
        ),
    ]
