# Generated by Django 4.2.5 on 2023-12-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_alter_newlycreatedproperty_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='discount_period',
        ),
        migrations.CreateModel(
            name='DiscountProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField(null=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.property')),
            ],
            options={
                'verbose_name_plural': 'Discount properties',
            },
        ),
    ]
