# Generated by Django 4.2.5 on 2023-12-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_remove_property_discount_period_discountproperty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='have_access_to_ARL',
        ),
        migrations.RemoveField(
            model_name='property',
            name='have_access_to_BTS_or_MRT',
        ),
    ]
