# Generated by Django 4.2.5 on 2024-01-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_remove_property_have_access_to_arl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymedia',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('interior_virtual_tour', 'Interior virtual tour')], max_length=100, null=True),
        ),
    ]
