# Generated by Django 4.2.5 on 2024-02-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_alter_propertymedia_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='interior_view',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
