# Generated by Django 4.2.5 on 2024-02-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_property_interior_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymedia',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=100, null=True),
        ),
    ]
