# Generated by Django 4.2.5 on 2024-03-06 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_alter_propertymedia_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountproperty',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='property.property'),
        ),
        migrations.AlterField(
            model_name='newlycreatedproperty',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newly_createds', to='property.property'),
        ),
        migrations.AlterField(
            model_name='popularproperty',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='populars', to='property.property'),
        ),
    ]
