# Generated by Django 4.2.5 on 2024-03-09 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0028_rename_have_access_to_arl_building_distance_from_location_to_arl_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0026_alter_discountproperty_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareproperty',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compares', to='property.property'),
        ),
        migrations.AlterField(
            model_name='compareproperty',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compare_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='building.building'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prospectfavoriteproperty',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='property.property'),
        ),
    ]
