# Generated by Django 4.2.5 on 2024-05-29 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_alter_compareproperty_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='visit_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
