# Generated by Django 4.2.5 on 2024-05-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0028_property_visit_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopularProperty',
        ),
    ]
