# Generated by Django 4.2.5 on 2024-06-27 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0030_spotlightproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='property.property')),
            ],
            options={
                'verbose_name_plural': 'Feature properties',
            },
        ),
        migrations.AddConstraint(
            model_name='featureproperty',
            constraint=models.UniqueConstraint(fields=('property',), name='unique_feature_property'),
        ),
    ]
