# Generated by Django 4.2.5 on 2024-07-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0031_featureproperty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotlightProperty',
        ),
    ]
