# Generated by Django 4.2.5 on 2024-07-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0032_delete_spotlightproperty'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='discountproperty',
            constraint=models.UniqueConstraint(fields=('property',), name='unique_discount_property'),
        ),
    ]
