# Generated by Django 4.2.5 on 2024-07-30 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0034_property_search_appearances_property_view_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('range', models.CharField(max_length=50, unique=True)),
                ('search_appearance', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='PropertyViewerLocation',
            new_name='PropertyVisitorLocation',
        ),
        migrations.RemoveField(
            model_name='property',
            name='search_appearances',
        ),
        migrations.AddField(
            model_name='property',
            name='female_visitors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='male_visitors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='search_appearance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PropertyDemography',
        ),
        migrations.AddField(
            model_name='propertyvisitlog',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.property'),
        ),
        migrations.AddField(
            model_name='propertyvisitlog',
            name='user_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
