# Generated by Django 4.2.5 on 2024-08-11 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0035_propertypricerange_propertyvisitlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='visit_count',
        ),
        migrations.CreateModel(
            name='PropertyClicksLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_clicked', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.property')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
