# Generated by Django 4.2.5 on 2024-10-08 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0036_create_property_visit_count_propertyclicklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountproperty',
            name='number_of_clicked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discountproperty',
            name='view_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
