# Generated by Django 4.2.5 on 2024-10-09 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0037_discountproperty_number_of_clicked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureproperty',
            name='number_of_clicked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='featureproperty',
            name='view_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
