# Generated by Django 4.2.5 on 2025-09-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0038_featureproperty_number_of_clicked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='have_bathtub',
            field=models.BooleanField(default=False, verbose_name='Bathtub'),
        ),
        migrations.AlterField(
            model_name='property',
            name='have_duplex',
            field=models.BooleanField(default=False, verbose_name='Duplex'),
        ),
        migrations.AlterField(
            model_name='property',
            name='have_owner_occupied',
            field=models.BooleanField(default=False, verbose_name='Owner Occupied'),
        ),
        migrations.AlterField(
            model_name='property',
            name='have_tenant_occupied',
            field=models.BooleanField(default=False, verbose_name='Tenant Occupied'),
        ),
        migrations.AlterField(
            model_name='property',
            name='have_vacant',
            field=models.BooleanField(default=False, verbose_name='Vacant'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
