# Generated by Django 4.2.5 on 2025-10-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0039_alter_property_have_bathtub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
