# Generated by Django 4.2.5 on 2025-10-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0040_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureproperty',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
