# Generated by Django 4.2.5 on 2025-10-15 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0041_featureproperty_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountproperty',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featureproperty',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discountproperty',
            name='period',
            field=models.DateField(null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='featureproperty',
            name='expiry_date',
            field=models.DateField(null=True, verbose_name='Expiry Date'),
        ),
    ]
