# Generated by Django 4.2.27 on 2025-12-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_agentprofile_credit_balance_and_more'),
        ('property', '0043_savedsearch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='savedsearch',
            name='unique_prospect_search_name',
        ),
        migrations.AlterUniqueTogether(
            name='savedsearch',
            unique_together={('prospect', 'name')},
        ),
    ]
