# Generated by Django 4.2.5 on 2023-11-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=500, null=True)),
                ('body', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
