# Generated by Django 4.2.5 on 2025-10-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initial_credit_balance_for_agent', models.DecimalField(decimal_places=2, default=0, help_text='Default starting credit for newly created agent profiles.', max_digits=10)),
                ('initial_credit_balance_for_developer', models.DecimalField(decimal_places=2, default=0, help_text='Default starting credit for newly created developer profiles.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Admin Setting',
                'verbose_name_plural': 'Admin Settings',
            },
        ),
    ]
