# Generated by Django 4.2.5 on 2025-10-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adminsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='discount_property_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Credit cost to create a discount property.', max_digits=10),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='featured_property_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Credit cost to create a featured property.', max_digits=10),
        ),
    ]
