# Generated by Django 4.2.5 on 2025-10-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_adminsettings_discount_property_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='OpenAI API key for ChatGPT integration.', max_length=500, null=True),
        ),
    ]
