# Generated by Django 4.2.27 on 2025-12-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adminsettings_openai_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='OpenRouter API key for AI chatbot integration. Get your key from https://openrouter.ai/', max_length=500, null=True),
        ),
    ]
