# Generated by Django 4.2.5 on 2023-09-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_confirmationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmationcode',
            old_name='is_active',
            new_name='is_valid',
        ),
        migrations.RemoveField(
            model_name='confirmationcode',
            name='is_used',
        ),
    ]
