# Generated by Django 4.2.5 on 2023-09-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_confirmationcode_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='email',
            field=models.EmailField(db_collation='case_insensitive', error_messages={'unique': 'Profile with this email already exists.'}, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='email',
            field=models.EmailField(db_collation='case_insensitive', error_messages={'unique': 'Profile with this email already exists.'}, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prospectprofile',
            name='email',
            field=models.EmailField(db_collation='case_insensitive', error_messages={'unique': 'Profile with this email already exists.'}, max_length=254, null=True, unique=True),
        ),
    ]
