# Generated by Django 4.2.5 on 2023-09-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_agentprofile_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospectprofile',
            old_name='Gender',
            new_name='gender',
        ),
    ]
