# Generated by Django 4.2.5 on 2023-10-03 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_confirmationcode_code_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='developerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='prospectprofile',
            name='email',
        ),
    ]
