version: '3'

services:
  web:
    restart: always
    build:
      context: .
    command: bash -c "gunicorn wizerproperties.wsgi:application --bind 0.0.0.0:8000 --reload --timeout 120 --workers 3"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_files:/app/wizerproperties/static_root/
      - media_files:/app/wizerproperties/media/
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=wizerproperties.settings
      - PYTHONUNBUFFERED=1

  db:
    restart: always
    image: postgres:15.4  # Use an appropriate PostgreSQL version
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5492:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB_HOST=${POSTGRES_HOST}
  
  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - static_files:/app/wizerproperties/static_root/
      - media_files:/app/wizerproperties/media/
    depends_on:
      - web

  certbot:
      image: certbot/certbot
      volumes: 
        - ./certbot/www/:/var/www/certbot/:rw
        - ./certbot/conf/:/etc/letsencrypt/:rw


volumes:
  postgres_data:
  static_files:
  media_files: