services:
  web:
    build:
      context: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .git
            - node_modules/
            - __pycache__/
            - "*.pyc"
        - action: rebuild
          path: requirements.txt
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=wizerproperties.settings
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:15.4  # Use an appropriate PostgreSQL version
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5492:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB_HOST=${POSTGRES_HOST}

  assets:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ..:/app
    command: sh -c "npm ci && npm run tailwind:watch"

volumes:
  postgres_data:
